## Target platform
platform :ios, '10.0'

## External source
source 'https://github.com/CocoaPods/specs.git'

## Use frameworks
use_frameworks!

def testing_pods
  pod 'Quick'
  pod 'Nimble'
end

def utilities_pods
	pod 'QRCodeReader.swift'
end

target 'CodiceFiscale_Example' do
  pod 'CodiceFiscale', :path => '../'
  
  utilities_pods

  target 'CodiceFiscale_Tests' do
    inherit! :search_paths

    testing_pods

  end
end
